version: '3.8'

networks:
  app:
    driver: bridge
    name: app_network

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      - app
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack
    container_name: localstack
    restart: always
    networks:
      - app
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"